baseurl = "https://kbroman.org/blog/"
relativeurls = true
languageCode = "en-us"
title = "the stupidest thing..."
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = "kbroman-blog"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$", "drafts/"]
rssLimit = 30

copyright="The text in this work is licensed under CC-BY-4.0, https://creativecommons.org/licenses/by/4.0/legalcode; code licensed under the MIT License"

[author]
    name="Karl Broman"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "about"
    url = "https://kbroman.org/blog/about"
[[menu.main]]
    name = "github"
    url = "https://github.com/kbroman"
[[menu.main]]
    name = "web"
    url = "https://kbroman.org"

[params]
    description = "Karl Broman's blog: The stupidest thing... statistics, genetics, programming, academics."
    disqusURL = "https://kbroman.org/blog"
    fullURL = "https://kbroman.org/blog"
    githubContentURL = "https://github.com/kbroman/blog/edit/source/content/"
    customCSS = ["css/custom.css"]

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "karl.png"
    width = 50
    height = 50
    alt = "Logo"
